// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRg2aHxEDiS8sdoAGyntVUsvpw1mjjfmI',
    appId: '1:100963189059:web:e8f970fae3945195aa2ff6',
    messagingSenderId: '100963189059',
    projectId: 'day-planner-4ba4b',
    authDomain: 'day-planner-4ba4b.firebaseapp.com',
    storageBucket: 'day-planner-4ba4b.firebasestorage.app',
    measurementId: 'G-8V8K10WE9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMyeU3y7dQB2Rkfam6jV9e0Npxpq4ADeA',
    appId: '1:100963189059:android:54c000a6f2dfde8baa2ff6',
    messagingSenderId: '100963189059',
    projectId: 'day-planner-4ba4b',
    storageBucket: 'day-planner-4ba4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT_VZtbJCUXsJnaQO7h8rL0rHNoMrYCao',
    appId: '1:100963189059:ios:003e46b8086ee581aa2ff6',
    messagingSenderId: '100963189059',
    projectId: 'day-planner-4ba4b',
    storageBucket: 'day-planner-4ba4b.firebasestorage.app',
    iosBundleId: 'com.example.trainingDayPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT_VZtbJCUXsJnaQO7h8rL0rHNoMrYCao',
    appId: '1:100963189059:ios:003e46b8086ee581aa2ff6',
    messagingSenderId: '100963189059',
    projectId: 'day-planner-4ba4b',
    storageBucket: 'day-planner-4ba4b.firebasestorage.app',
    iosBundleId: 'com.example.trainingDayPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRg2aHxEDiS8sdoAGyntVUsvpw1mjjfmI',
    appId: '1:100963189059:web:0deafe5c206091fbaa2ff6',
    messagingSenderId: '100963189059',
    projectId: 'day-planner-4ba4b',
    authDomain: 'day-planner-4ba4b.firebaseapp.com',
    storageBucket: 'day-planner-4ba4b.firebasestorage.app',
    measurementId: 'G-38635MFHQQ',
  );
}
